### ISSUE TITLE
Improve Dockerfile

### ISSUE THREAD

**Issue by Addono** [Addono/secret-hitler#20]
**Is your feature request related to a problem? Please describe.**
Current Dockerfile is very basic, which wastes resources and violates best practices w.r.t. security.

**Describe the solution you'd like**
- [ ] Version pinning of the base image
- [x] Using a lighter base image, e.g. `alpine` or `slim` #72
- [x] Switch to another user, as to prevent running the container as root #73 
- [x] Look into using multi-stage image, as to prevent including features in the final image which are only used for building. #72

If anyone wants to work on this, feel free to make a PR. Preferably seperate PRs (or commits) for individual improvements. But if you're comfortable, then doing it all at once is also fine.

**Comment by Addono** [comment]
#72
